# Generated by Django 5.2.5 on 2025-09-06 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rodas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corrida',
            name='motivo_cancelamento',
            field=models.TextField(blank=True, null=True, verbose_name='Motivo do Cancelamento'),
        ),
    ]
